version: '3.4'

services:
  node:
    image: relyte/stargaze-docker:0.1.3
    ports: 
      - "26657:26657"
      - "1317:1317"
      - "26656:26656"
    env_file:
      - container.env
    volumes:
      - ${CONFIG_DIR}:/root/.starsd/config
      - ${DATA_DIR}:/root/.starsd/data